/*
 * Copyright (c) 2026 LUSSAC PRESTES MAIA
 *
 * Released under the MIT License
 * See the LICENSE file in the project root for details.
 */
package io.github.lussac7.taskmanager.domain;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Immutable, append-only record of a system action.
 * Answers: <b>"Who did what, to which object, and when?"</b>
 *
 * <p><b>Design:</b> No setters — once created, never modified.
 * Generic target via {@code targetType + targetId} (not FK) so any entity
 * can be audited. Actor is lazy-loaded to avoid unnecessary JOINs.</p>
 *
 * <p><b>Usage:</b> Created exclusively by
 * {@link io.github.lussac7.taskmanager.service.AuditService}.</p>
 *
 * @see AuditAction
 * @see io.github.lussac7.taskmanager.service.AuditService
 */
@Entity
@Table(name = "audit_entries")
public class AuditEntry {

    // =========================================================================
    // FIELDS
    // =========================================================================
    // Each field answers one part of the "who did what" question.
    // All fields are set in the constructor and never changed (no setters).

    /** Primary key. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** What happened: CREATED, COMPLETED, DELETED, or ASSIGNED. Stored as VARCHAR. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AuditAction action;

    /**
     * Who performed the action.
     * Lazy-loaded: the User is only fetched from the database if you access
     * its fields (like getUsername()). This avoids unnecessary JOINs when
     * you just want the audit entry itself.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actor_id", nullable = false)
    private User actor;

    /**
     * The type of object that was acted upon.
     * Examples: "Task", "User", "Notification".
     * Combined with targetId, this uniquely identifies the target without
     * needing a foreign key for every entity type.
     */
    @Column(nullable = false)
    private String targetType;

    /**
     * The ID of the object that was acted upon.
     * Example: if targetType="Task" and targetId=42, the action was on Task #42.
     */
    @Column(nullable = false)
    private Long targetId;

    /**
     * Exactly when the action occurred.
     * Set automatically in the constructor to LocalDateTime.now().
     * Never modified after creation.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * Human-readable description of what happened.
     * Limited to 500 characters. Examples:
     * - "Task created: Complete project report"
     * - "Task assigned to user bob"
     * - "Task marked complete"
     */
    @Column(length = 500)
    private String details;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Protected no-arg constructor required by JPA.
     * JPA uses this via reflection when loading entities from the database.
     * It's protected (not public) so application code can't create incomplete
     * audit entries with null fields.
     */
    protected AuditEntry() {}

    /**
     * Creates a complete audit entry.
     * The timestamp is automatically set to the current moment.
     * The ID is null until the entity is persisted.
     *
     * @param action     what happened (CREATED, COMPLETED, DELETED, ASSIGNED)
     * @param actor      who performed the action
     * @param targetType type of object affected (e.g., "Task")
     * @param targetId   ID of the object affected
     * @param details    human-readable description
     */
    public AuditEntry(AuditAction action, User actor, String targetType,
                      Long targetId, String details) {
        this.action = action;
        this.actor = actor;
        this.targetType = targetType;
        this.targetId = targetId;
        this.details = details;
        this.timestamp = LocalDateTime.now();  // Auto-set to current time
    }

    // =========================================================================
    // GETTERS (NO SETTERS — audit entries are immutable)
    // =========================================================================
    // Once created, an audit entry should never change. This is the core
    // principle of audit logging: it's a permanent, tamper-proof record.

    public Long getId() { return id; }
    public AuditAction getAction() { return action; }
    public User getActor() { return actor; }
    public String getTargetType() { return targetType; }
    public Long getTargetId() { return targetId; }
    public LocalDateTime getTimestamp() { return timestamp; }
    public String getDetails() { return details; }
}