/*
 * Copyright (c) 2026 LUSSAC PRESTES MAIA
 *
 * Released under the MIT License
 * See the LICENSE file in the project root for details.
 */
package io.github.lussac7.taskmanager.domain;

import jakarta.persistence.*;

/**
 * A notification message sent to a user about a task event.
 *
 * <p>Currently logged to console and persisted. Future: email, push, in-app delivery.
 * Created only when the recipient has {@link User#isNotificationEnabled()} == true.</p>
 *
 * @see User
 * @see Task
 * @see io.github.lussac7.taskmanager.service.NotificationService
 */
@Entity
@Table(name = "notifications")
public class Notification {

    // =========================================================================
    // FIELDS
    // =========================================================================

    /** Primary key. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The notification text.
     * Example: "Task updated: Complete project report".
     * Never null — every notification must have content.
     */
    @Column(nullable = false)
    private String message;

    /**
     * The task that triggered this notification.
     * Lazy-loaded: the Task is only fetched from the database if you access
     * its fields beyond the ID. In most cases, only the task title is needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id")
    private Task task;

    /**
     * The user who will receive this notification.
     * Lazy-loaded: the User is only fetched if you need their email, username, etc.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User recipient;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /**
     * Protected no-arg constructor required by JPA.
     * JPA uses this via reflection when loading entities from the database.
     */
    protected Notification() {}

    /**
     * Creates a new notification. The ID is null until persisted.
     *
     * @param message   the notification text (must not be null)
     * @param task      the related task (may be null for system notifications)
     * @param recipient the user to notify (must not be null)
     */
    public Notification(String message, Task task, User recipient) {
        this.message = message;
        this.task = task;
        this.recipient = recipient;
    }

    // =========================================================================
    // GETTERS
    // =========================================================================

    public Long getId() { return id; }
    public String getMessage() { return message; }
    public Task getTask() { return task; }
    public User getRecipient() { return recipient; }
}