/*
 * Copyright (c) 2026 LUSSAC PRESTES MAIA
 *
 * Released under the MIT License
 * See the LICENSE file in the project root for details.
 */
package io.github.lussac7.taskmanager.domain;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Central domain entity — a unit of work with an owner and optional assignee.
 *
 * <h2>Business Rules (enforced here, not in services)</h2>
 * <ul>
 *   <li>{@link #markComplete()} — one-way transition: false → true. Throws if already done.</li>
 *   <li>{@link #updateTitle(String)} — title cannot be null or blank.</li>
 *   <li>{@code createdAt} is immutable ({@code updatable = false}).</li>
 * </ul>
 *
 * <h2>Relationships</h2>
 * <ul>
 *   <li>{@code owner} — Composition (NOT NULL, cascade delete).</li>
 *   <li>{@code assignedTo} — Simple Association (nullable, no cascade).</li>
 * </ul>
 *
 * @see User
 * @see io.github.lussac7.taskmanager.service.TaskService
 */
@Entity
@Table(name = "tasks")
public class Task {

    // =========================================================================
    // FIELDS
    // =========================================================================

    /** Primary key. Auto-generated by the database when the task is first persisted. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short description of what needs to be done. Must not be blank. */
    @Column(nullable = false)
    private String title;

    /** Optional longer description. Limited to 1000 characters. */
    @Column(length = 1000)
    private String description;

    /**
     * Whether the task is done.
     * One-way transition: false → true. Once true, NEVER goes back to false.
     * This rule is enforced by markComplete().
     */
    @Column(nullable = false)
    private boolean isComplete = false;

    // -------------------------------------------------------------------------
    // RELATIONSHIPS
    // -------------------------------------------------------------------------

    /**
     * The user who created and owns this task (Composition).
     * NOT NULL — every task must have a creator.
     * If the owner is deleted, this task is cascade-deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /**
     * The user assigned to work on this task (Simple Association).
     * Nullable — a new task starts unassigned.
     * No cascade — deleting a user does NOT delete tasks assigned to them.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to_id")
    private User assignedTo;

    /**
     * When the task was created.
     * Set once in the constructor. Hibernate will never include this column
     * in UPDATE statements (updatable = false).
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Optional deadline for the task.
     * Null means "no deadline" — the task can sit in the backlog indefinitely.
     */
    @Column
    private LocalDate dueDate;

    /**
     * Comma-separated list of attachment filenames.
     * Files are stored on disk in the uploads/ directory.
     * Only the filenames are stored here.
     * Example: "abc123-report.pdf,def456-image.png"
     */
    @Column(length = 2000)
    private String attachments;

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /** JPA-required protected no-arg constructor. */
    protected Task() {}

    /**
     * Creates a new task.
     * createdAt is auto-set to now. isComplete starts as false.
     * assignedTo starts as null (unassigned).
     *
     * @param title       short description (must not be blank)
     * @param description optional details (may be null)
     * @param owner       the user who owns this task (must not be null)
     */
    public Task(String title, String description, User owner) {
        this.title = title;
        this.description = description;
        this.owner = owner;
        this.createdAt = LocalDateTime.now();
    }

    // =========================================================================
    // DOMAIN METHODS (Business Logic)
    // =========================================================================
    // These methods enforce business rules at the entity level.
    // No matter where they're called from, the rules are always applied.

    /**
     * Marks this task as complete. Cannot be undone.
     *
     * <p>This is a one-way state machine: false → true.
     * There is no "un-complete" operation — once done, always done.
     * This models the real world: you can't un-finish something.</p>
     *
     * @throws IllegalStateException if the task is already completed
     */
    public void markComplete() {
        // Guard: prevent double-completion
        if (this.isComplete) {
            throw new IllegalStateException("Task is already completed");
        }
        this.isComplete = true;
    }

    /**
     * Updates the title after validating it's not blank.
     *
     * <p>The validation lives HERE (in the entity), not in the service or
     * controller. This means ANY code that calls updateTitle() is protected
     * by the same rule — even if someone adds a new feature in the future.</p>
     *
     * @throws IllegalArgumentException if title is null or blank (whitespace only)
     */
    public void updateTitle(String newTitle) {
        if (newTitle == null || newTitle.isBlank()) {
            throw new IllegalArgumentException("Title cannot be blank");
        }
        this.title = newTitle;
    }

    /**
     * Assigns this task to a user (or unassigns by passing null).
     * No business restrictions — can assign completed tasks, reassign freely.
     */
    public void setAssignedTo(User user) {
        this.assignedTo = user;
    }

    // =========================================================================
    // GETTERS & SETTERS
    // =========================================================================

    public Long getId() { return id; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public boolean isComplete() { return isComplete; }
    public User getOwner() { return owner; }
    public User getAssignedTo() { return assignedTo; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDate getDueDate() { return dueDate; }
    public String getAttachments() { return attachments; }

    public void setDueDate(LocalDate dueDate) { this.dueDate = dueDate; }
    public void setAttachments(String attachments) { this.attachments = attachments; }

    // =========================================================================
    // EQUALS & HASHCODE (JPA Best Practice)
    // =========================================================================
    // Two Task objects are equal if they have the same database ID.
    // Before persistence (ID is null), they're compared by identity.
    // This prevents: treating two new objects as equal, and treating
    // two loaded objects as different when they represent the same row.

    /** JPA best practice: equality based on ID. */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;                       // Same reference
        if (!(o instanceof Task task)) return false;       // Wrong type
        return id != null && Objects.equals(id, task.id);  // Same ID (if not null)
    }

    /**
     * Fixed hash before persistence, ID-based after.
     * Using getClass().hashCode() ensures all new (unpersisted) entities
     * have the same hash, which is safe because they're compared by identity.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    // =========================================================================
    // TO STRING
    // =========================================================================
    // Excludes relationships (owner, assignedTo) to avoid triggering
    // lazy-loading during logging. Accessing owner.getUsername() in a
    // toString() would cause an unexpected database query.

    /** Excludes relationships to avoid lazy-loading triggers during logging. */
    @Override
    public String toString() {
        return "Task{id=" + id + ", title='" + title + "', isComplete=" + isComplete + "}";
    }
}