/*
 * Copyright (c) 2026 LUSSAC PRESTES MAIA
 *
 * Released under the MIT License
 * See the LICENSE file in the project root for details.
 */
package io.github.lussac7.taskmanager.domain;

import jakarta.persistence.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Objects;

/**
 * Represents a system user. Implements {@link UserDetails} to serve as both
 * a domain entity AND a Spring Security principal — no separate adapter needed.
 *
 * <p><b>Password storage:</b> BCrypt-hashed. Raw passwords are never persisted.</p>
 * <p><b>Roles:</b> USER or ADMIN. ADMIN inherits USER permissions via role hierarchy.</p>
 * <p><b>Notifications:</b> Opt-out — enabled by default.</p>
 *
 * @see UserRole
 * @see Task
 */
@Entity
@Table(name = "users")
public class User implements UserDetails {

    // =========================================================================
    // FIELDS
    // =========================================================================

    /** Primary key. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique login name.
     * The {@code unique = true} creates a database index that enforces
     * uniqueness AND speeds up login lookups (findByUsername).
     */
    @Column(nullable = false, unique = true)
    private String username;

    /** User's email address. Used for notifications (future email delivery). */
    @Column(nullable = false)
    private String email;

    /**
     * BCrypt-hashed password. The raw password is NEVER stored here.
     * Hashing happens in UserController (via passwordEncoder.encode()) or
     * DataInitializer before the entity is persisted.
     * During login, Spring Security hashes the submitted password and
     * compares hashes — plaintext comparison never occurs.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Whether the user wants notifications.
     * Default: true (opt-out model — users get notifications unless they
     * explicitly disable them).
     * Checked by the opt[] guard in Sequence Diagrams before sending.
     */
    @Column(nullable = false)
    private boolean isNotificationEnabled = true;

    /**
     * The user's role: USER or ADMIN.
     * Stored as VARCHAR (EnumType.STRING) for readability and safety
     * against enum reordering.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRole role = UserRole.USER;

    // -------------------------------------------------------------------------
    // RELATIONSHIPS
    // -------------------------------------------------------------------------

    /**
     * Tasks owned by this user (Composition).
     *
     * <p>mappedBy = "owner" means the Task entity owns the relationship
     * (it has the foreign key column).</p>
     *
     * <p>cascade = ALL means operations on the User cascade to their Tasks.
     * Deleting a User deletes all their Tasks.</p>
     *
     * <p>orphanRemoval = true means if a Task is removed from this list,
     * it's deleted from the database.</p>
     *
     * <p>transient: not included in Java serialization (avoids SonarQube
     * warning about non-serializable JPA collections).</p>
     */
    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
    private final transient List<Task> ownedTasks = new ArrayList<>();

    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================

    /** JPA-required protected no-arg constructor. */
    protected User() {}

    /**
     * Creates a new user.
     *
     * @param username unique login name
     * @param email    user's email address
     * @param password MUST be already BCrypt-hashed — callers are responsible for encoding
     * @param role     USER or ADMIN
     */
    public User(String username, String email, String password, UserRole role) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    // =========================================================================
    // UserDetails IMPLEMENTATION (Spring Security Integration)
    // =========================================================================
    // These methods are called by Spring Security during authentication and
    // authorization. They fulfill the UserDetails contract.

    /**
     * Converts the user's role to a Spring Security authority.
     * USER → ROLE_USER, ADMIN → ROLE_ADMIN.
     *
     * <p>Spring Security checks these authorities against the rules in
     * SecurityConfig (e.g., .hasRole("ADMIN")).</p>
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // Creates a single-element immutable list.
        // Example: new SimpleGrantedAuthority("ROLE_USER")
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    /** Returns the BCrypt-hashed password. Never the raw password. */
    @Override
    public String getPassword() { return password; }

    /** Returns the username used for login. */
    @Override
    public String getUsername() { return username; }

    // =========================================================================
    // ACCOUNT STATUS METHODS
    // =========================================================================
    // All return true because this application doesn't implement account
    // expiration, locking, credential rotation, or disabling.
    // If you add these features, change the return values to check actual fields.

    /** @return always true — account expiration is not implemented */
    @Override public boolean isAccountNonExpired() { return true; }

    /** @return always true — account locking is not implemented */
    @Override public boolean isAccountNonLocked() { return true; }

    /** @return always true — credential rotation is not implemented */
    @Override public boolean isCredentialsNonExpired() { return true; }

    /** @return always true — account disabling is not implemented */
    @Override public boolean isEnabled() { return true; }

    // =========================================================================
    // DOMAIN METHODS
    // =========================================================================

    /**
     * Hook for future audit logging of login events.
     * Currently a no-op — authentication is handled by Spring Security.
     */
    public void login(String password) {
        // No-op: authentication is handled by Spring Security's DaoAuthenticationProvider.
        // This method exists as a hook for future audit logging (e.g., recording lastLoginTimestamp).
    }

    /**
     * Hook for future audit logging of logout events.
     * Currently a no-op — session management is handled by Spring Security.
     */
    public void logout() {
        // No-op: session invalidation is handled by Spring Security's SecurityContextLogoutHandler.
        // This method exists as a hook for future audit logging of logout events.
    }

    /**
     * Returns whether the user wants to receive notifications.
     * Checked by the opt[] guard condition in the Sequence Diagrams.
     */
    public boolean isNotificationEnabled() { return isNotificationEnabled; }

    /** Enables or disables notifications for this user. */
    public void setNotificationEnabled(boolean enabled) { this.isNotificationEnabled = enabled; }

    /** Convenience method — returns true if the user has ADMIN role. */
    public boolean isAdmin() { return this.role == UserRole.ADMIN; }

    /** Sets the user's role. Used by admin user management. */
    public void setRole(UserRole role) { this.role = role; }

    /**
     * Sets the password. The value must ALREADY be BCrypt-hashed.
     * Used by admin user creation and password changes.
     */
    public void setPassword(String password) { this.password = password; }

    // =========================================================================
    // GETTERS
    // =========================================================================

    public Long getId() { return id; }
    public String getEmail() { return email; }
    public UserRole getRole() { return role; }
    public List<Task> getOwnedTasks() { return ownedTasks; }

    // =========================================================================
    // EQUALS & HASHCODE (JPA Best Practice)
    // =========================================================================
    // Two User objects are equal if they have the same database ID.
    // Before persistence, they're compared by identity.

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User user)) return false;
        return id != null && Objects.equals(id, user.id);
    }

    @Override
    public int hashCode() { return getClass().hashCode(); }

    // =========================================================================
    // TO STRING
    // =========================================================================
    // Excludes password (security) and task list (avoids lazy-loading trigger).

    @Override
    public String toString() {
        return "User{id=" + id + ", username='" + username + "', role=" + role + "}";
    }
}